repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest discover tests
        language: python
        "types": [python]
        ## args: ["-p '*test.py'"] # Probably this option is absolutely not needed.
        pass_filenames: false
        stages: [commit]
        additional_dependencies: [requests]
