name: DEPLOY:pypi_test

on:
  push:
    tags:
      - "v*-DEV"
    branches:
      - "develop"
      - "main"
  pull_request:
    branches:
      - develop
      - main

jobs:
  test_unittest:
    name: Deploy pypi_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements-dev.txt
      - name: Deploy
        env:
          TEST: ${{ secrets.TEST_SECRET }}
        run: |
          echo "$TEST"
