name: Publish to PyPI Test

env:
  REPO_OWNER_USERNAME: ${{ secrets.REPO_OWNER_USERNAME }}

on:
  workflow_dispatch:
    permissions:
      users:
        - $REPO_OWNER_USERNAME

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Unittest Tests
        run: |
          python -m unittest discover tests -p '*_test.py'

  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Check Version
        id: check_version
        run: |
          set +e
          LAST_VERSION=$(grep "__version__ = .*" nsdpy.py | sed " s/__version__ = //")
          echo "last version is $LAST_VERSION"
          REGEXP='.*-beta$'
          echo "$REGEXP"
          TEST=$(grep ".*-beta" <<< "$LAST_VERSION")
          echo "$TEST"
          if echo "$LAST_VERSION" | grep -qP "$REGEXP";
          then
          echo "Last version: $LAST_VERSION"
          else
          echo "Version is not a test version: should end with -beta"
          fi
          echo "Last version: $LAST_VERSION"
          echo "last_version=$LAST_VERSION" >> $GITHUB_OUTPUT

      - name: Check for Existing Tag
        id: increment_version_and_check_tag
        run: |
          set +e
          LAST_VERSION=${{ steps.check_version.outputs.last_version }}
          echo "looking for a matching tag..."
          git fetch --tags --quiet
          TAG_EXISTS=$(git tag -l "$LAST_VERSION")
          if [ -z "$TAG_EXISTS" ]; then
          echo "No matching tags found for version $LAST_VERSION"
          exit 1
          fi
          echo "matching tag $TAG_EXISTS found"
          echo "checking tag isSemVer..."
          SEMVER="^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
          if echo "$TAG_EXISTS" | grep -qP "$SEMVER";
          then
          echo "$TAG_EXISTS is SemVer-compliant"
          else
          echo "$TAG_EXISTS is not SemVer-compliant"
          exit 1
          fi
          echo "$TAG_EXISTS is SemVer-compliant"
          echo "tags=$TAG_EXISTS" >> $GITHUB_OUTPUT

      - name: Build and Publish to PyPI Test
        env:
          BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
        if: steps.increment_version_and_check_tag.outputs.tag_exists != '1'
        run: |
          echo "Publishing to PyPI test..."
          poetry build
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi $BOT_ACCESS_TOKEN
          poetry publish -r test-pypi
