name: TESTS:unittest

on: [push, pull_request]

jobs:
  test_unittest:
    name: Tests unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements-dev.txt
      - name: Test
        run: python3 -m unittest discover tests
