name: TESTS:unittest

on: [push, pull_request]

jobs:
  test_unittest:
    name: Tests unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pwd
          pip3 install -r ./github/workflow/requirements-dev.txt
      # - name: Build package
      #   run: python -m build
      - name: Test
        run: python3 -m discover unittest
